<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        <?php echo $error . PHP_EOL; ?>
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body>
<!-- Content //-->
<div id="content">
    <h1 style="color: #f00;"><?php echo $error; ?></h1>
    <p>That page was not found.</p>
</div>
<!-- Footer //-->
</body>

</html>
