<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        <?php echo $title . PHP_EOL; ?>
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body>
<!-- Content //-->
<div id="content">
    <h1><?php echo $title; ?></h1>
    <p>This is a basic "hello world" application example.</p>
</div>
<!-- Footer //-->
</body>

</html>
