#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
CYG_PATH="$( which cygpath )"

if [ "$CYG_PATH" != "" ]; then
    SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\pop.php $@"
    SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
else
    SCRIPT_PATH="$SCRIPT_DIR/pop.php $@"
fi

php $SCRIPT_PATH

